config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users

  resources :users
  resources :events do
  	resource :posts
    resource :pledges
    resource :trainingsessions
    # resource :challenges

    collection do
      get 'select'
    end

    resources :posts do
      resource :comments
    end

    resources :challenges do
      get :create_challenge_post, on: :collection
    end

  end

  resources :trainingsessions

  get 'users/:user_id/events', to: 'users#events', as: :user_events
  get 'users/:user_id/profile', to: 'users#profile', as: :profile
  post 'trainingsessions/:event_id/mmf', to: 'trainingsessions#mmf', as: :mmf_training
  post '/challenge/:id/accept', to: 'challenges#accept'
  post '/challenge/:id/decline', to: 'challenges#decline'
  get 'events/:id/donations', to: 'events#donations', as: :donations
  get '/auth/:provider/callback', to: 'identities#create'
  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>

</head>

<body>
<section class='hp-upper-container'>
	<section class='hp-cover-image'>

		<section class="main-image-search">
      <section class="user_management">
      <% if user_signed_in? %>
          <%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete, class: 'lets_go-button', id:'sign_out'%>
      <% end %>
      </section>

			<%= form_tag(users_path, :method => "get", id: "search-form") do %>
  			<%= text_field_tag :search, params[:search], class: 'find_person', placeholder: "Looking for a friend..?" %>
  			<%= submit_tag "GO", id:'search_button' %>
			<% end %>
		</section>

			<h2 class='main-image-header'>CHALLENGE.ME</h2>
			<h5 class='main-image-text'>FUNDRAISING JUST GOT FUN </h5>
			<section class='cover-image-button-container'>
      <video autoplay muted loop poster="<%= asset_path('click.jpg')%>" id="bgvid">
        <source src="<%= asset_path('ldn_360.mp4') %>" type="video/mp4">
      </video>
				<%= link_to "START", select_events_path, class: 'lets_go-button' %>
					<%= link_to "EVENTS", events_path, class: 'lets_go-button' %>
			</section>
		</section>
	</section>

</body>

</html>