config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users

  resources :users
  resources :events do
  	resource :posts
    resource :pledges
    resource :trainingsessions
    # resource :challenges

    collection do
      get 'select'
    end

    resources :posts do
      resource :comments
    end

    resources :challenges do
      get :create_challenge_post, on: :collection
    end

  end

  resources :trainingsessions

  get 'users/:user_id/events', to: 'users#events', as: :user_events
  get 'users/:user_id/profile', to: 'users#profile', as: :profile
  post 'trainingsessions/:event_id/mmf', to: 'trainingsessions#mmf', as: :mmf_training
  post '/challenge/:id/accept', to: 'challenges#accept'
  post '/challenge/:id/decline', to: 'challenges#decline'
  get 'events/:id/donations', to: 'events#donations', as: :donations
  get '/auth/:provider/callback', to: 'identities#create'
  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, format: { with: /\A[A-Z,a-z]/}, length: {minimum: 3}
  validates :event_date, presence: true
  validates :charity, presence: true
  validates :target, presence: true, numericality: true
  validates :amount_raised, presence: true, numericality: true
  validate :not_past_date
  validates :training, presence: true
  validates :user_id, uniqueness: {scope: :jg_event_id, message: 'You have already created the same event'}

  has_many :posts, dependent: :destroy
  has_many :pledges, dependent: :destroy
  has_many :challenges
  has_many :trainingsessions, dependent: :destroy
  belongs_to :user

  def not_past_date
    if event_date.present? && event_date < Date.today
      errors.add(:event_date, 'not in past')
    end
  end

  def percentage_of_target
    ((amount_raised/target)*100).to_i
  end

  def next_pledge
     pledges.select{ |pledge| pledge.amount.to_f > amount_raised }.min_by{|pledge| pledge.amount }
  end

  def is_owner? user
    return false if user.nil?
    self.user_id == user.id
  end

  def weekly_training_sessions
    trainingsessions.count{|session| session.sessiondate.cweek == Date.today.cweek}
  end

  def days_to_event
    ((event_date.to_time - created_at) / 3600) / 24
  end

  def percentage_of_weekly_workouts_complete
    ((self.weekly_training_sessions.to_f / self.training)*100).round
  end

  def validate_mmf_data

    client = connect_to_api
    client.workouts.each do |workout|

      workout_date, workout_name = assign_from_hash(workout)

      if valid_new_workout?(workout_date, workout)
        trainingsession = trainingsessions.new(details: workout_name, sessiondate: workout_date)
        if route_logged?(workout)
          trainingsession.mmf_updated_datetime = workout["updated_datetime"]
          trainingsession.mmf_route_id = (workout['_links']['route'][0]["id"]).to_s
        end
        trainingsession.save
      end
    end

  end

private

  def previously_logged?(workout)
    logged_workouts = trainingsessions.all
    logged_workouts.any?{|logged| logged.details == workout["name"]}
  end

  def route_logged?(workout)
    workout['_links'].include?("route")
  end

  def connect_to_api
   Mmf::Client.new do |config|
      config.client_key    = Rails.application.secrets.map_my_api_key
      config.client_secret = Rails.application.secrets.map_my_api_secret
      config.access_token  = user.identities.find_by(provider: 'mapmyfitness').token
    end
  end

  def assign_from_hash(workout)
      workout_date =  workout["start_datetime"].slice(0..(workout["start_datetime"].index('T'))).chop
      [workout_date, workout['name'].empty? ? "Workout on #{workout_date}" : workout['name'] ]
  end

  def valid_new_workout?(workout_date, workout)
    workout_date.to_date >= created_at.to_date && !previously_logged?(workout)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show, :donations]

  def index
    @events = Event.all
  end

  def new
    existing_event = Event.find_by(jg_short_name: params[:page_short_name])
    redirect_to event_path(existing_event) if existing_event
    just_giving_data = JustGiving::Fundraising.new(params[:page_short_name]).page
    @event = Event.new(format_event_with(just_giving_data))
  end

  def create
    @event = Event.new(params[:event].permit(:name, :event_date, :charity, :target, :amount_raised, :training, :jg_event_id, :jg_short_name, :jg_page_id))
    @event.user = current_user
    if @event.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @event_id = @event.id
    @user = @event.user
    @posts = @event.posts.order(created_at: :desc)
    @comment = Comment.new
    @pledges = @event.pledges
    @challenges = @event.challenges.where(status: nil)
    @trainingsession = @event.trainingsessions.new
    @trainingsessions = @event.trainingsessions.all
  end

  def edit
    @event = current_user.events.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = 'You are not the owner of the event'
    redirect_to root_path
  end

  def update
    @event = Event.find(params[:id])
    @event.update(params[:event].permit(:name, :event_date, :charity, :target, :amount_raised))
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.is_owner? current_user
      @event.destroy
      flash[:notice] = 'Deleted Successfully'
      redirect_to events_path
    else
      flash[:alert] = 'You are not the owner of the event'
      redirect_to root_path
    end
  end

  def select
    @events = JustGiving::Account.new(current_user.email).pages || []
  end

  def donations
    @event = Event.find(params[:id])
    @fundraising = JustGiving::Fundraising.new(@event.jg_short_name).page
    @event.amount_raised = @fundraising['grandTotalRaisedExcludingGiftAid'].to_f
    @event.save
    redirect_to event_path(@event)
  end

  private
  def format_event_with(api_hash)
    return if api_hash.nil? || api_hash.is_a?(Array)
    {name: api_hash['eventName'],
    event_date: format(api_hash['eventDate']),
    charity: api_hash['charity']['name'],
    target: api_hash['fundraisingTarget'],
    amount_raised: api_hash['grandTotalRaisedExcludingGiftAid'],
    jg_event_id: api_hash['eventId'],
    jg_short_name: api_hash['pageShortName'],
    jg_page_id: api_hash['pageId'] }
  end

  def format(event_date)
    date_string = event_date.match(/\(([0-9]+)/)[1]
    Time.at(date_string.to_i / 1000).to_date
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def display_if(test_environment)
    return ''if test_environment
    'display:none;'
  end
end

app/views/events/_event.html.erb
<%= link_to event_path(event), class: "event-container" do %>
  <h2><%= event.name%></h2>
  <p><%= icon('smile-o', event.user.full_name) %></p>
  <p><%= icon('calendar', event.event_date.strftime("%d %B %Y")) %></p>
  <p><%= icon('gift', event.charity) %></p>
  <section class="event-states">
    <ul>
      <li>
        <strong><%= event.percentage_of_target %> %</strong>
        Funded
      </li>
      <li>
        <strong>£<%= event.amount_raised.round %></strong>
        Donated
      </li>
      <li>
        <strong><%= (event.event_date - Date.today).to_i %></strong>
        days to go
      </li>
    </ul>
  </section>

  <!-- Targetbar -->
<section class="mini-target-bar-container" data-event-id='<%= event.id %>'>
  <div class="mini-target-wrap mini-progress" data-progress-percent="">
    <div class="mini-target-bar mini-progress">
    </div>
  </div>
</section>

<%= javascript_tag do %>
  showMiniProgressBar("<%=j event.amount_raised.to_s %>", "<%=j event.target.to_s %>", <%= event.id %>);
<% end %>

<% end %>

app/views/events/_form.html.erb
<section class='main-form-container'>
  <%= form_for @event do |f| %>
    <% if @event.errors.any? %>
    <section class='errors-container'>
      <article class="error-explanation">
        <p class='errors-title'>
          <%=pluralize(@event.errors.count, "error") %>
          prevented this event from being saved:
        </p>
        <ul class='error-message'>
          <% @event.errors.full_messages.each do |message| %>
            <li>- <%=message%></li>
          <%end%>
        </ul>
      </article>
    </section>
    <%end%>

    <section class="new-event-form">

    <p class='event-form-label'>
      <%= f.label :name %>
    </p>
      <%= f.text_field :name, class: 'event-form-input', placeholder: 'full name' %>

    <p class='event-form-label'>
      <%= f.label :event_date, 'Event Date', :order => [:day, :month, :year] %>
    </p>
    <section class='date-select-container'>
      <%= f.date_select :event_date, class: 'event-form-input' %>
    </section>
    
    <p class='event-form-label'>
      <%= f.label :charity %>
    </p>
      <%= f.text_field :charity, class: 'event-form-input', placeholder: 'charity name' %>

    <p class='event-form-label'>
      <%= f.label :target, 'Fundraising Target (£)' %>
    </p>

      <%= f.text_field :target, class: 'event-form-input', placeholder: "what's your target?" %>

    <p class='event-form-label'>
      <%= f.label :amount_raised, 'Amount Raised (£)' %>
    </p>
      <%= f.text_field :amount_raised, class: 'event-form-input', placeholder: '(leave empty if nothing)' %>

    <p class='workout-selection-text'>
      Workout target p/week
    </p>
    <p class='workout-selection-form'>
      <section class='workouts-button-container'>
        <%= f.radio_button(:training, 2, id:'2-workouts') %> 
        <%= f.label(:training, 2, id: '2-workouts-label') %>
        <%= f.radio_button(:training, 3, id:'3-workouts') %> 
        <%= f.label(:training, 3, id: '3-workouts-label') %>
        <%= f.radio_button(:training, 4, id:'4-workouts') %> 
        <%= f.label(:training, 4, id: '4-workouts-label') %>
        <%= f.radio_button(:training, 5, id:'5-workouts') %> 
        <%= f.label(:training, 5, id: '5-workouts-label') %>
        <%= f.radio_button(:training, 6, id:'6-workouts') %> 
        <%= f.label(:training, 6, id: '6-workouts-label') %>
      </section>
    </p>
    <%= f.hidden_field :jg_event_id %>
    <%= f.hidden_field :jg_short_name %>
    <%= f.hidden_field :jg_page_id %>
    <%= f.submit(id: 'submit-event') %>
      

    </section>
  <% end %>
</section>

app/views/events/_pledge_modal.html.erb
<div id="new-pledge-modal" style="display:none;">
  <%= form_for [@event, @event.pledges.new ], as: :pledge, url: event_pledges_path(@event) do |f| %>
  	<p id="menu-header">I PROMISE</p>
        <section class='pledge-modal-container'>
            <%= f.label :amount, "Once I raise...", id: 'pledge-modal-label' %>   <%= f.text_field :amount, id: 'pledge-modal-input', placeholder: 'set a £ amount' %>
        </section>
        
        <section class='pledge-modal-container'>
           <%= f.label :caption, "I will...", id: 'pledge-modal-label' %>
           <%= f.text_field :caption, id: 'pledge-modal-input', placeholder: 'what do you promise to do?' %>
        </section>
        
        <section class='pledge-modal-container'>
          <%= f.label :text, "Tell us more!", id: 'pledge-modal-label' %>
          <%= f.text_field :text, id: 'pledge-modal-input', placeholder: "further details go here" %>
         </section>
  
        <section class="pledge-create-modal">
          <%= f.submit 'GO', class: 'modal-button-create' %>
        	<a class='close-modal' href="#" rel="modal:close">Close</a>
        </section>
  <%end%>
</div>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<%if @events.any?%>
  <section class="main-form-container">
    <%= render @events.reverse %>
  </section>
<% else %>
  <h3>There are no events at the moment.</h3>
<%end%>
<%= link_to 'Add Your Event', select_events_path %>

app/views/events/mapmyrun.html.erb
<% if @event.is_owner?(current_user) %>
        <p class='log-training-button-container'>
         <%= link_to "Log training session", new_event_trainingsessions_path(@event), class: 'modal-button', id: 'log-training-button', data: { :'modal-selector' => '#ex1' }  %>
         </p>
        <%end%>
          <!-- sync with mapmyfitness -->
<% if current_user == @event.user %>
  <section class='map-my-fitness'>

    <p class='mapmyfitness-sync-text'>
      Map<br> My<br> Fitness:
    </p>
    <section class='mmf-button'>
      <%= image_tag("sync.png", id: 'sync-icon') %>
      <%= link_to "Sync", mmf_training_path(@event.id), id: 'map-my-fitness-button-text', method: :post %>
      </section>
  </section>
   <%end%>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/select.html.erb
<section class='select-jg-event-background'>
	<section class='select-jg-event-container'>
		<p class='user-welcome-message'>
			Hello <%= current_user.firstname %>!
		</p>
			<%if @events.any?%>
			<section class='select-event-form'>
			<div id="select-event-form-header">Import an event from Just Giving or create a new one with Challenge Me.</div>
			<section class='jg-events-container'>
			<% if @events.any? %>
			<img src='http://mastcharity.co.uk/wp-content/uploads/2014/06/JUSTGIVING-LOGO.jpg' id='justgiving-logo'>
			<% end %>
		  <% @events.each_with_index do |event, index| %>
		    <%= link_to "#{event['eventName'].upcase}", new_event_path(page_short_name: event['pageShortName']), class: 'event-select-button' %>
		  <% end %>
		  </section>
		  	<div id="events-select-logo">Challenge.Me</div>
		    <%= link_to 'CREATE NEW EVENT', new_event_path, class: 'event-select-button', id: 'create-new-event-button' %>
			<%else %>
		  <%= link_to 'CREATE NEW EVENT', new_event_path, class: 'event-select-button', id: 'create-new-event-button' %>
			<% end %>
		</section>
	</section>
</section>

app/views/events/show.html.erb
  <section class='container-left' id='event-page'>
    <section class='logo-container'><a href='/' class='events-page-logo'>Challenge.Me</a>
    </section>

    <section class='picture-container'>
      <section class='profile-picture' >
        <div id='profile-image'>
            <% if @event.is_owner?(current_user) %>
              <%= link_to '#', class: "profilepic-modal-button"  do %>
                <%= icon('camera', '',class:'icon-camera', data: { :'modal-selector' => '#profilepic-modal' }) %>
              <% end %>
            <% end %>
          <% if @event.user.avatar.present? %>
            <%= image_tag @event.user.avatar.url(:medium), class: 'profile-pic'  %>
          <% end %>
        </div>
      </section>
      <p id='event-user-name'>
        <%= @event.user.firstname.capitalize %> <%= @event.user.lastname.capitalize %>
      </p>
    </section>



    <section class='donate-button-container'>
      <% if @event.is_owner? current_user %>
          <a href="#menu-modal" rel="modal:open" class='menu-modal-button' >MENU</a>
     <% else %>

      <section class='challenge-me'>
        <%= link_to 'Challenge Me', '#', class: 'challenge-me-button', id: "challenge-me-link", data: { :'modal-selector' => '#new-challenge-modal' } %>
        </section>
      <% end %>
    </section>

    <section class='training-stats'>
      <section class='training-headline'>
        <p id='training-section-headline'>TRAINING</p>
      </section>





    <section class='workouts-completed-by-user'>
      <p id='workouts-completed-head'>
        This week is<br>
      </p>
      <p id='workouts-completed-number'>
      <div class="progress-radial progress-<%= @event.percentage_of_weekly_workouts_complete %>">
        <div class="overlay"><%= @event.percentage_of_weekly_workouts_complete %>%</div>
      </div>
      </p>
      <p id='workouts-completed-footer'>
          done
      </p>

    </section>

     <section class='training-totals'>
      <p id='training-goal-headline'>GOAL</p>
      <p id='training-goal-number'><%= @event.training %></p>
      <p id='training-goal-text'>sessions per week.</p>
    </section>

 <section class='recent-workout-details'>
        <% if @trainingsessions.any? %>

          <p id='recent-workout-details-head'><%= @event.user.firstname.upcase %>'S <br>LAST WORKOUT
            <p id='workouts-completed-footer'><%= @trainingsessions.last.details %></p>

          </p>
       <%end%>
    </section>


     <section class='total-completed-workouts'>
        <p id='workouts-completed-total-number'>
           <%= @event.trainingsessions.count%></p>
        <p id='workouts-completed-total-text'>
         workouts completed <br>overall
        </p>
      </section>

  <section class='share'>
   <%= render_shareable buttons: ['twitter'] %>
  </section>
  </section>
</section>

<section class='main-content-container'>

  <section class='container-top'>

    <section id='timeleft-container'>
  <section id='timeleft-details-container'>
  <p>
    £<%=@event.amount_raised.to_i %> RAISED SO FAR - 
   <% if (@event.event_date == Date.today) %>
      Today's the day!
    <% elsif (@event.event_date > Date.today) %>
       <%=  "#{(@event.event_date - Date.today).to_i}" %> DAYS TO GO
    <% else %>
      Event completed <%= "#{(Date.today - @event.event_date).to_i}" %> days ago!
    <% end %>
    </p>
  </section>
</section>
  <section class='pledge-container'>
      <section class='event-details-container'>
        <p id='event-paragraph'><%= @event.user.firstname.capitalize %> is fundraising for <strong><%= @event.charity %></strong> by <%= @event.name %> on <strong><%= @event.event_date.strftime("%d %B '%y") %></strong></p>
      </section>
</section>

  <section class='fundraising-stats'>

  <section id="progress-background">
<section class='tags'>
    <aside id="bar_000" class="divider"><span>£0</span></aside>
    <aside id="bar_025" class="divider"><span>£<%= (@event.target*0.25).to_i %></span></aside>
    <aside id="bar_050" class="divider"><span>£<%= (@event.target*0.5).to_i %></span></aside>
    <aside id="bar_075" class="divider"><span>£<%= (@event.target*0.75).to_i %></span></aside>
    <aside id="bar_100" class="divider"><span>£<%= @event.target %></span></aside>
</section>

    <section id="progress">
  <%= javascript_tag do %>
              amountRaised = "<%=j @event.amount_raised.to_s %>";
              targetAmount = "<%=j @event.target.to_s %>";
  <% end %>

    <aside id="bar"></aside>
    <aside id="bar_000" class="divider"><span>0%</span></aside>
    <aside id="bar_025" class="divider"><span>25%</span></aside>
    <aside id="bar_050" class="divider"><span>50%</span></aside>
    <aside id="bar_075" class="divider"><span>75%</span></aside>
    <aside id="bar_100" class="divider"><span>£<%= @event.target %></span></aside>
  </section>


</section>



</section>

    <% @challenges.each do |challenge| %>
      <% if current_user == @event.user %>
        <section class='challenge-display'>
          <section class='challenge-text'>
            <p class='challenger-creator'>
              You've been challenged by <%= challenge.creator %>!
            </p>
            <p class='challenger-description'>
              Challenge: <%= challenge.name %><br>
              For a £<%=challenge.amount%> donation
            </p>
          </section>
          <section class='challenge-button-container', data-challenge="<%= challenge.id %>">
            <button class='accept-challenge'><i class="fa fa-check"></i></button>
            <button class='decline-challenge'><i class="fa fa-times"></i></button>
          </section>
        </section>
        <% else %>
          <section class='challenge-text'>
              <p class='challenger-creator'>
                You have set <%= @event.user.firstname %> a challenge! Will <%= @event.user.firstname %> accept?
              </p>
            </section>
      <%end%>
    <% end %>



  <section class='donations-container'>
  <% if current_user == @event.user %>
      <%= link_to 'UPDATE SPONSORS', new_event_posts_path(@event), class: 'new-post-modal-button', id: "update-sponsers-link", data: { :'modal-selector' => '#new-post-modal' } %>
      <%= link_to "MAKE A PROMISE", new_event_pledges_path(@event), class: 'new-post-modal-button', id: "make-a-promise-link", data: { :'modal-selector' => '#new-pledge-modal' } %>
  <% else %>
  <%= link_to 'DONATE', just_giving_fundraising_donation_url("#{@event.jg_page_id}", {exit_url: "#{request.original_url}/donations"}), id: "donate-button" %>
    <%end%>
  </section>

  <section class='update-feed'>
    <% if @posts.any? %>
    <section id="cd-timeline" class="cd-container">
      <%= render @posts %>
    </section>
    <% else %>
      There are no posts
    <% end %>
  </section>
</section>



  <div id="new-post-modal" style="display:none;">
    <% @post = @event.posts.new %>
    <%= form_for [@event, @post], html: { multipart: true } do |f| %>
    <p id="menu-header">UPDATE</p>
      <% if @post.errors.any? %>
      <article class="error_explaination">
        <%= pluralize(@post.errors.count, "error") %>
        prevent this event from being saved:
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%=message%></li>
          <% end %>
        </ul>
      </article>
    <% end %>

      <section class="post-caption-modal">
        <%= f.label :caption, id: 'pledge-modal-label' %>
        <%= f.text_field :caption, id: 'pledge-modal-input', placeholder: "write a title for your post here..."%>
      </section>
      <br>
      <button id="post-picture" class="modal-button-create"><%= icon('file-image-o ')%>  PICTURE</button>
      <button id="post-video" class="modal-button-create"><%= icon('youtube')%>  VIDEO</button>
      <button id="post-text" class="modal-button-create"><%= icon('pencil')%>  TEXT</button>


      <section class="post-picture-modal">
        <%= f.label :picture, id: 'pledge-modal-label' %>
        <%= f.file_field :picture %>
      </section>


      <section class="post-video-modal">
        <%= f.label :video, id: 'pledge-modal-label' %>
        <%= f.text_field :video, id: 'pledge-modal-input',id: 'pledge-modal-input', placeholder: "paste a youtube URL here..." %>
      </section>

      <section class="post-text-modal">
        <%= f.label :text, id: 'pledge-modal-label' %>
        <%= f.text_field :text, id: 'pledge-modal-input', id: 'pledge-modal-input', placeholder: "write some hilarious content here..." %>
      </section>
      <br>
      <section  class="post-create-modal">
        <%= f.submit 'Create post', class: 'modal-button-create' %>
      </section>
    <% end %>
  </div>

  <div id="ex1" style="display:none;">
    <%= form_for [@event, @trainingsession] do |f| %>
    <section class='modal-header'>
      <%= f.label :details, "Training details"%>
    </section>
    <section class='modal-body'>
      <%= f.text_area :details %>
       <%= f.label :sessiondate, 'Training Session Date' %>
      <article class='training-date-selector'>
        <%= f.date_select :sessiondate, :order => [:day, :month, :year] %>
      </article>
    </section>
    <section class="modal-footer">
      <%= f.submit 'Add Workout', class: 'modal-button-create' %>
      <a class='close-modal' href="#" rel="modal:close">Close</a>
    </section>
    <%end%>

  </div>

  <div id="new-challenge-modal" style="<%= display_if(Rails.env.test?) %>">
    <%= form_for [@event, @event.challenges.new] do |f| %>
      <p id="menu-header">SET A CHALLENGE</p>
      <section class="challenge-creator-modal">
        <%= f.label :creator, 'Challenger', id: 'pledge-modal-label' %>
        <%= f.text_field :creator, class: 'pledge-modal-input', placeholder: "What's your name?" %>
      </section>

      <section class="challenge-name-modal">
        <%= f.label :name, 'Describe your challenge', id: 'pledge-modal-label' %>
        <%= f.text_field :name, class: 'pledge-modal-input', placeholder: "what do you want them to do?" %>
      </section>
      <section class="challenge-amount-modal">
        <%= f.label :amount, 'How much would you donate?', id: 'pledge-modal-label' %>
        <%= f.text_field :amount, class: 'pledge-modal-input', placeholder: "£££" %>
      </section>
      <section  class="challenge-create-modal">
        <%= f.submit 'Create challenge', class: 'modal-button-create' %>
      </section>

    <%end%>
  </div>




  <div id="menu-modal" style="<%= display_if(Rails.env.test?) %>">
   <p id="menu-header">MENU</p>

   <% if @event.is_owner?(current_user) %>
      <section class='modal-body'>
  -      <%= link_to 'MY EVENTS', user_events_path(current_user), class:"menu-event"%><br>
  -      <%= link_to "EDIT EVENT", edit_event_path(@event), id: "edit-link", class:"menu-event" %><br>
  -      <%= link_to "DELETE EVENT", event_path(@event), class:"menu-event", id: "delete-event", method: :delete %><br>
  -      <%= link_to "CREATE EVENT", new_event_path,class:"menu-event" %><br>
  -      <%= link_to "LOG TRAINING", new_event_trainingsessions_path(@event), class: 'modal-button', class:"menu-event", id: "log-workout", data: { :'modal-selector' => '#ex1' } %><br>
  -      <%= link_to "SYNC MAPMYFITNESS", mmf_training_path(@event.id), class:"menu-event", id: 'sync-mmf', method: :post %><br>
  -      <%= link_to'SIGN OUT', destroy_user_session_path, method: :delete, class:"menu-event" %>
      </section>
    <% end %>

  </div>
    <%= render "events/pledge_modal" %>
    <div id="profilepic-modal" style="<%= display_if(Rails.env.test?) %>">
    <%= render "users/profilepic" %>
  </div>