config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users

  resources :users
  resources :events do
  	resource :posts
    resource :pledges
    resource :trainingsessions
    # resource :challenges

    collection do
      get 'select'
    end

    resources :posts do
      resource :comments
    end

    resources :challenges do
      get :create_challenge_post, on: :collection
    end

  end

  resources :trainingsessions

  get 'users/:user_id/events', to: 'users#events', as: :user_events
  get 'users/:user_id/profile', to: 'users#profile', as: :profile
  post 'trainingsessions/:event_id/mmf', to: 'trainingsessions#mmf', as: :mmf_training
  post '/challenge/:id/accept', to: 'challenges#accept'
  post '/challenge/:id/decline', to: 'challenges#decline'
  get 'events/:id/donations', to: 'events#donations', as: :donations
  get '/auth/:provider/callback', to: 'identities#create'
  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :picture, styles: { medium: "300x300#" },
    storage: :s3,
    s3_credentials: {
      bucket: 'challengeme',
      access_key_id: Rails.application.secrets.s3_access_key_id,
      secret_access_key: Rails.application.secrets.s3_access_access_key
    }

	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  validates :caption, length: {maximum: 140, minimum: 3, message: "Your caption must be between 3 and 140 characters"}
  validate :is_youtube_address
	belongs_to :event
  belongs_to :user

  has_many :comments

  def is_youtube_address
    if video.present? && !video.include?("youtube.com/watch?v=")
      errors.add(:video, 'not a YouTube video url')
    end
  end

  def is_owner? user
    return false if user.nil?
    self.user_id == user.id
  end

  def video_id
    video.partition('=').last
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!

	def new
		@event = Event.find(params[:event_id])
		@post = @event.posts.new
	end

	def create
		@event = Event.find(params[:event_id])
		@post = @event.posts.new(params[:post].permit(:caption, :picture, :video, :text))
		@post.user = current_user
		if @post.save
			redirect_to event_path(@event)
		else
			render 'new'
		end
	end

	def edit
		@event = Event.find(params[:event_id])
		@post = @event.posts.find(params[:id])
		unless @post.is_owner? current_user
			flash[:notice] = 'You are not the owner of the post'
			redirect_to '/'
		end
	end

	def update
		@event = Event.find(params[:event_id])
		@post = Post.find(params[:id])
		@post.update(params[:post].permit(:caption, :picture, :video, :text))
		redirect_to event_path(@event)
	end

	def destroy
		@event = Event.find(params[:event_id])
		@post = Post.find(params[:id])
		if @post.is_owner? current_user
			 @post.destroy
			flash[:notice] = 'Deleted Post Successfully'
			redirect_to event_path(@event)
		else
			flash[:alert] = 'You are not the owner of the post'
			redirect_to root_path
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
  def time_line_image(post)
    return 'cd-icon-picture.svg' if post.picture.present?
    return 'cd-icon-movie.svg' if post.video.present?
    'cd-icon-location.svg'
  end

  def time_line_class(post)
    return 'cd-picture' if post.picture.present?
    return 'cd-movie' if post.video.present?
    'cd-location'
  end
end

app/views/posts/_post.html.erb
<div class="cd-timeline-block">
  <div class="cd-timeline-img <%= time_line_class(post) %>">
    <img src="<%= asset_path(time_line_image(post)) %>" alt="Picture">
  </div> <!-- cd-timeline-img -->

  <div class="cd-timeline-content">
    <h2><%= post.caption %></h2></br>
        <% if post.is_owner?(current_user) %>
        <%= link_to 'Edit Post', edit_event_post_path(@event, post), class: 'edit-post' %>
        <%= link_to 'Delete Post', event_post_path(@event, post), class: 'delete-post', method: :delete %>
      <% end %>
    <% if post.picture.present? %>
      <section class="picture-post">
        <%= image_tag post.picture.url(:medium), class: 'uploaded-pic'  %>
      </section>
    <% elsif post.video.present? %>
        <section class="video-post">
        <object width="297" height="206">
          <param name="movie"
                 value="https://www.youtube.com/v/<%=post.video_id%>?version=3&autoplay=0"></param>
          <param name="allowScriptAccess" value="always"></param>
          <embed src="https://www.youtube.com/v/<%=post.video_id%>?version=3&autoplay=0"
                 type="application/x-shockwave-flash"
                 allowscriptaccess="always"
                 width="400" height="300"></embed>
        </object>
         </section>
    <%elsif post.url.present? %>
    <iframe id="mapmyfitness_route" src="<%=post.url%>" height="263px" width="100%" frameborder="0"></iframe>
    <% elsif post.text.present? %>
      <article class="text-post">
        <p><%= post.text %></p>
      </article>
    <%end%>
    <span class="cd-date">Posted by <%= post.event.user.full_name%> <%= time_ago_in_words(post.created_at) %> ago
    </span>
    <section class="comments-container">
      <% if post.comments.any? %>
      <section class="comments-list">

          <% post.comments.reverse_each do |comment| %>
            <article class="comment">
              <section class="comment-text"><%= comment.comments %>
                <section><strong><%= comment.user.full_name %></strong> - <%= time_ago_in_words(comment.created_at) %></section>
              </section>
            </article>
          <% end %>

      </section>
              <% end %>
      <section class='comments-input-container'>
        <%= form_for [@event, post, @comment] do |f| %>
          <%= f.text_field :comments, id: 'comments-placeholder', placeholder: 'Thoughts..?' %>
          <%= button_tag(type: 'submit', id: 'comment-submit-button') do %>
            <%= icon('comment') %>
          <% end %>
        <% end %>
      </section>
    </section>
  </div>
</div>

app/views/posts/_postform.html.erb
<%= form_for [@event,@post], html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <article class="error_explaination">
      <%= pluralize(@post.errors.count, "error") %>
        prevent this event from being saved:
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%=message%></li>
          <% end %>
        </ul>
    </article>
  <% end %>

	<%= f.label :caption %>
	<%= f.text_field :caption %>

  Choose the type of post :

	<%= f.label :picture %>
	<%= f.file_field :picture %>

    or </br>

  <%= f.label :video %>
  <%= f.text_field :video %>

    or </br>

  <%= f.label :text %>
  <%= f.text_field :text %>

	<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<%= render 'postform' %>

app/views/posts/index.html.erb
<section class='update-feed'>
  <% if @posts.any? %>
    <%= render @posts %>
  <% else %>
    There are no posts
  <% end %>
</section>

app/views/posts/new.html.erb
<%= form_for [@event,@post], html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <article class="error_explaination">
      <%= pluralize(@post.errors.count, "error") %>
        prevent this event from being saved:
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%=message%></li>
          <% end %>
        </ul>
    </article>
  <% end %>

	<%= f.label :caption %>
	<%= f.text_field :caption %>

	<%= f.label :picture %>
	<%= f.file_field :picture %>

	<%= f.submit 'Create Post' %>

<% end %>